all: paging.c paging_w.c paging_r.c
	gcc -g -O0 -std=c99 -Wall -Wextra -o paging paging.c
	gcc -g -O0 -std=c99 -Wall -Wextra -o paging_w paging_w.c
	gcc -g -O0 -std=c99 -Wall -Wextra -o paging_r paging_r.c



